version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
platform: x86
clone_depth: 3

install:
- git submodule update --init --recursive
- git submodule update --recursive
- '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"'

build_script:
- cd win32
- build.cmd

after_build:
- 7z a SciTEX.zip dist

artifacts:
- path: win32\SciTEX.zip
